Bubble sort feature
Azeem838/bubble-sort pull request #1
Opened 2020-05-04 10:14 UTC by Azeem838

This pull request contains the following 2 methods:

1. bubble_sort takes an array and returns a sorted array
2. bubble_sort_by takes an array and a block and sorts the array based on the block.

Kindly find our commit below.

2020-05-04 23:38 UTC, uryelah requested changes
Hello **Abdoulaye Razak & Azeem Mahomed Ahmed**, I'm Sarah, your reviewer for this PR 👩‍🚀  

Great job guys, your methods pass all the required test cases!

I just can't approve you right away because you kept the debugging code in your file. Make sure to delete those before submitting, the file should have only the two methods.

--------

## **Changes Required**

**Check the comments below for details on the required changes:**

2020-05-04 23:38 UTC, uryelah commented on bubble_sort.rb
> +  p array
- [ ] just return the 'array', not 'p array'

2020-05-04 23:38 UTC, uryelah commented on bubble_sort.rb
> +unsorted_list = [6, 2, 8, 1, 7, 3, 4]
- [ ] Please remove the debugging code before submiting for review. You should submit only the methods. (1)

2020-05-04 23:38 UTC, uryelah commented on bubble_sort.rb
> +bubble_sort(unsorted_list)
- [ ] Please remove the debugging code before submitting it for review. You should submit only the methods. (2)

2020-05-04 23:38 UTC, uryelah commented on bubble_sort.rb
> +bubble_sort_by(%w[hi hello hey]) do |left, right|
- [ ] Please remove the debugging code before submitting it for review. You should submit only the methods. (1)

2020-05-04 23:38 UTC, uryelah commented
**Kindly fix the pointed out issues before requesting the next code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-05-05 23:07 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team,  You have done a great job with this project. :clap:
#### You can go ahead and merge !!!

2020-05-06 07:00 UTC, merged